# Generated by Django 5.2.4 on 2025-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0002_alter_notification_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='logwork',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
