# Generated by Django 5.2.4 on 2025-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0003_job_title_alter_logwork_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
