# Generated by Django 5.2.4 on 2025-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('Vender', 'Vender')], max_length=20, null=True),
        ),
    ]
