# Generated by Django 5.2.4 on 2025-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'deleted'), ('I', 'inactive'), ('A', 'active'), ('U', 'unverified')], max_length=20, null=True),
        ),
    ]
