# Generated by Django 5.2.4 on 2025-08-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user__notifications_user__social_user_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_social',
        ),
    ]
