# Generated by Django 5.2.4 on 2025-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user__notifications_remove_user__social'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_notifications',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='user',
            name='_social',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
