# Generated by Django 5.2.4 on 2025-08-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user__notifications_user__social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('welder', 'Welder'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
