# Generated by Django 5.2.4 on 2025-07-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_activation_expiry_user_activation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
    ]
