# Generated by Django 5.2.4 on 2025-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('vendor', 'Vendor'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
