# Generated by Django 5.2.4 on 2025-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='default123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
